name: Release Beta

on:
  push:
    tags:
      - "v*-beta*"

permissions:
  contents: write

jobs:
  release-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser.beta.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
